---
title: "00_introduction"
author: "Wyclife Agumba Oluoch"
format: html
editor: visual
---

## Quarto

Introduction to sdm

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
library(sdm)
library(terra)
library(geodata)
```

You can add options to executable code like this

```{r}
#| echo: false

file <- system.file("external/species.shp", package="sdm") # get the location of the species data

species <- vect(file) # read the shapefile

path <- system.file("external", package="sdm") # path to the folder contains the data

lst <- list.files(path=path,pattern='asc$',full.names = T) # list the name of the raster files 


# stack is a function in the raster package, to read/create a multi-layers raster dataset
preds <- rast(lst) # making a raster object

d <- sdmData(formula=Occurrence~., train=species, predictors=preds)

d

# fit the models (5 methods, and 10 replications using bootstrapping procedure):
m <- sdm(Occurrence~.,data=d,methods=c('rf','mars','svm'),
          replicatin='boot',n=3)
p1 <- ensemble(m, newdata=preds, setting=list(method='weighted',stat='AUC'))
plot(p1)
    
```

The `echo: false` option disables the printing of code (only output is displayed).
